my_string = input('gimme a string: ')
print('The variable "my_string" = ',my_string)
biggest = max(my_string)
print('The biggest character in the \nstring "STEAM Is Cool" is','"'+biggest+'".')
smallest = min(my_string)
print('The smallest character in the \nstring "STEAM Is Cool" is','"'+smallest+'".')
# print('Done with Challenge 1')
